name: Generate JKS Key

on:
  workflow_dispatch: # 允许你在网页上手动触发执行

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate JKS
        run: |
          # 1. 生成密码为 123456，别名为 pixelpilot 的金钥
          keytool -genkey -v \
            -keystore pixelpilot.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias pixelpilot \
            -storepass 123456 \
            -keypass 123456 \
            -dname "CN=PixelPilot, OU=Dev, O=PixelPilot, L=HK, S=HK, C=HK"

          # 2. 自动转换成无换行符的 Base64 纯文字
          base64 -w 0 pixelpilot.jks > base64_clean.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pixelpilot-keys
          path: |
            pixelpilot.jks
            base64_clean.txt
